blank_issues_enabled: false
contact_links:
  - name: Official Discord
    url: https://discord.gg/neosvr
    about: A place to find the latest patch notes, previews of features undergoing active development, general discussion of Neos, and help from other users.
  - name: Neos Moderation Center
    url: https://moderation.neos.com
    about: Please report security vulnerabilities here.
